# FROM alpine:3.5
FROM alpine@sha256:0c8da65d4500db7421cc95021208989b850804c9214352f48dc5ffbd351387f4

# copy package info early to install npms and delete npm command
WORKDIR /usr/src/app
COPY package*.json ./
RUN apk -U add bash nodejs && \
  npm install 

# copy the code
COPY . .
EXPOSE 3000
ENTRYPOINT ["node","server.js"]
